# Generated by Django 3.1 on 2020-08-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20200826_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='displayname',
        ),
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
